spring:
  application:
    name: short link application local environment
  datasource:
    url: jdbc:postgresql://localhost:5432/db_short_link
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database: postgresql
server:
  address: "localhost"
  port: 8080
